---
- name: Converge
  hosts: all
  tasks:
    - name: Update APT
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: "Include appsembler_ops_agent_config_role"
      include_role:
        name: "appsembler_ops_agent_config_role"
